runtime: php55
api_version: 1

handlers:
- url: /getAll.php
  script: getAll.php
- url: /createList.php
  script: createList.php
- url: /deleteMovie.php
  script: deleteMovie.php
- url: /createMovie.php
  script: createMovie.php
- url: /deleteList.php
  script: deleteList.php